## FEATURE ENGINEERING 
Is the process of using domain knowledge to select, create, or transform raw data into meaningful features (input variables) that make machine learning models work more effectively.
Here we perform variuos operatiosn like feature transformation(missing value handling, outlier treatment, handeling categorical data, scaling), feature construction, feature selection, feature extraction

## Feature transformation

In [3]:
import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('Housing.csv')

In [5]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

### Scaling
Machine learning models learn from numerical features, and features with larger magnitudes can disproportionately influence the model’s decisions. To prevent any single feature from dominating due to its scale, we apply scaling techniques. Scaling transforms all feature values to a similar range or magnitude, ensuring that each feature contributes fairly to the model’s performance.

In [21]:
X=df[['area']]
y=df['price']

#### Here we will use Standard scaling as we have variuos types of scaling available like min-max scaling,

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y, test_size=0.25,random_state=42)

In [23]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)

In [24]:
X_train

     area
167  4600
368  5640
301  3520
527  1836
382  3150
..    ...
71   6000
106  5450
270  4500
435  4040
102  5500

[408 rows x 1 columns]

In [25]:
X_train_scaled

array([[-2.49346791e-01],
       [ 2.22626972e-01],
       [-7.39473390e-01],
       [-1.50370783e+00],
       [-9.07387132e-01],
       [ 2.40779809e-01],
       [-1.36347716e+00],
       [ 1.33902645e+00],
       [-5.53406811e-01],
       [ 5.76607293e-01],
       [-4.62642626e-01],
       [ 2.85478834e+00],
       [ 2.05016384e+00],
       [ 2.36466174e+00],
       [ 3.67849668e-01],
       [-1.02991878e+00],
       [ 5.49378038e-01],
       [-7.57626227e-01],
       [ 1.33902645e+00],
       [ 6.31065804e-01],
       [-1.07212413e+00],
       [ 6.03836549e-01],
       [-7.03167716e-01],
       [-8.91503400e-01],
       [-3.35572767e-01],
       [ 1.74746528e+00],
       [-6.80476670e-01],
       [ 9.12434778e-01],
       [-7.10428851e-01],
       [-3.94569487e-01],
       [ 8.39823430e-01],
       [ 2.02883425e+00],
       [ 1.82279955e+00],
       [-1.35666985e+00],
       [ 4.08693551e-01],
       [ 1.74746528e+00],
       [ 7.74042754e-02],
       [ 1.65670110e+00],
       [ 1.52055482e+00],
       [ 3.31543994e-01],
       [ 3.65351317e+00],
       [-2.90190674e-01],
       [-4.87602777e-01],
       [-7.44011599e-01],
       [-1.04081048e+00],
       [ 3.86002505e-01],
       [-2.94728883e-01],
       [ 6.58295060e-01],
       [-7.44011599e-01],
       [-2.67499628e-01],
       [-7.57626227e-01],
       [-1.24866047e+00],
       [-7.48549809e-01],
       [ 1.06673389e+00],
       [ 7.94441337e-01],
       [ 3.86002505e-01],
       [ 4.13231760e-01],
       [-7.03167716e-01],
       [ 6.58295060e-01],
       [-3.85493068e-01],
       [-1.72197233e-01],
       [-5.03486509e-01],
       [ 1.06673389e+00],
       [-9.05094669e-02],
       [ 6.83278569e-02],
       [ 3.86002505e-01],
       [ 1.15114458e+00],
       [-8.55651547e-01],
       [ 6.58295060e-01],
       [-4.98948300e-01],
       [-6.85014879e-01],
       [ 1.59092042e-01],
       [-5.76097857e-01],
       [ 3.51736689e+00],
       [ 3.86002505e-01],
       [ 5.01497594e+00],
       [ 9.30587615e-01],
       [ 1.03950464e+00],
       [-8.66543249e-01],
       [ 1.74746528e+00],
       [-1.05850950e+00],
       [-1.40429769e-01],
       [ 5.76607293e-01],
       [-1.36347716e+00],
       [ 7.49059245e-01],
       [-8.80157877e-01],
       [ 1.13709949e-01],
       [ 2.11052202e+00],
       [-2.94728883e-01],
       [-3.76416650e-01],
       [-2.03964698e-01],
       [ 1.36171749e+00],
       [-4.67180835e-01],
       [-7.57626227e-01],
       [-4.76257253e-01],
       [ 3.17929366e-01],
       [-1.65389920e-01],
       [-5.21639346e-01],
       [ 6.85524315e-01],
       [-7.71240855e-01],
       [ 1.15749808e+00],
       [-2.94728883e-01],
       [ 3.86002505e-01],
       [-4.03645905e-01],
       [ 2.58932646e-01],
       [-5.39792183e-01],
       [-5.03486509e-01],
       [-5.21639346e-01],
       [-1.58582606e-01],
       [-5.21639346e-01],
       [ 6.65102374e-01],
       [ 1.59092042e-01],
       [-6.78184207e-02],
       [-1.58582606e-01],
       [ 1.13709949e-01],
       [-2.94728883e-01],
       [-7.48549809e-01],
       [ 1.40709959e+00],
       [-7.93931901e-01],
       [-9.48231016e-01],
       [-5.07117076e-01],
       [ 5.44839828e-01],
       [-7.66702646e-01],
       [-5.03486509e-01],
       [-1.49506187e-01],
       [-1.21371626e+00],
       [ 8.48899848e-01],
       [-3.67340231e-01],
       [-6.21479950e-01],
       [ 3.53733501e+00],
       [ 2.29457644e-02],
       [-1.15245043e+00],
       [-7.03167716e-01],
       [-8.43852203e-01],
       [-1.36347716e+00],
       [ 3.79195191e-01],
       [ 1.05856512e+00],
       [ 5.49378038e-01],
       [-7.39473390e-01],
       [-6.89553088e-01],
       [ 3.86002505e-01],
       [ 1.46246574e+00],
       [ 2.95238320e-01],
       [-9.96789855e-01],
       [-6.35094577e-01],
       [-5.89712485e-01],
       [-6.09877484e-03],
       [-1.22276932e-01],
       [-6.16034098e-01],
       [ 3.86002505e-01],
       [-1.19329432e+00],
       [ 3.62403816e-01],
       [-1.36347716e+00],
       [ 2.42819667e+00],
       [-5.27992839e-01],
       [ 1.59092042e-01],
       [ 1.40709959e+00],
       [ 1.13709949e-01],
       [ 9.85046126e-01],
       [-1.11160655e+00],
       [ 1.74746528e+00],
       [-1.58582606e-01],
       [-5.21639346e-01],
       [-6.89553088e-01],
       [ 5.67530875e-01],
       [-1.58811852e+00],
       [-3.35572767e-01],
       [ 9.98660754e-01],
       [ 5.01273020e-01],
       [ 1.28456794e+00],
       [-4.67180835e-01],
       [-7.39473390e-01],
       [-1.34940871e+00],
       [ 1.32995003e+00],
       [-7.43103957e-01],
       [-5.21639346e-01],
       [-7.71240855e-01],
       [-3.76416650e-01],
       [ 4.74268339e+00],
       [ 9.08804211e-01],
       [ 5.31679022e-01],
       [-9.75460271e-01],
       [ 8.39823430e-01],
       [ 2.86386476e+00],
       [-8.59712577e-02],
       [-7.66702646e-01],
       [-9.75460271e-01],
       [-6.89553088e-01],
       [ 1.13709949e-01],
       [-1.13200513e-01],
       [ 1.59092042e-01],
       [-5.21639346e-01],
       [-6.85014879e-01],
       [-2.94728883e-01],
       [-2.94728883e-01],
       [-3.85493068e-01],
       [-8.93772505e-01],
       [-9.07387132e-01],
       [-2.94728883e-01],
       [-7.39473390e-01],
       [-5.03486509e-01],
       [-3.40110976e-01],
       [-4.78526358e-01],
       [-4.49027998e-01],
       [-7.03167716e-01],
       [ 3.08852947e-01],
       [ 7.08215362e-01],
       [-7.14489881e-02],
       [ 1.13709949e-01],
       [-1.06622446e+00],
       [-5.03486509e-01],
       [-6.37363682e-01],
       [ 1.29364436e+00],
       [ 6.31065804e-01],
       [-6.85014879e-01],
       [ 2.31020323e+00],
       [-9.75460271e-01],
       [-5.21639346e-01],
       [-8.16622947e-01],
       [ 6.12912967e-01],
       [-8.12084738e-01],
       [ 6.80986106e-01],
       [-1.13429760e+00],
       [-1.05034072e+00],
       [ 5.76607293e-01],
       [-1.81273652e-01],
       [-7.03167716e-01],
       [-1.58582606e-01],
       [-8.93772505e-01],
       [ 3.86002505e-01],
       [ 6.31065804e-01],
       [ 1.69300677e+00],
       [-3.58263813e-01],
       [ 1.40709959e+00],
       [-6.85014879e-01],
       [ 2.84117371e+00],
       [ 3.31543994e-01],
       [-9.07387132e-01],
       [ 6.35604013e-01],
       [ 8.39823430e-01],
       [ 1.27095331e+00],
       [ 1.59092042e-01],
       [ 2.42819667e+00],
       [-9.44146627e-01],
       [-5.89712485e-01],
       [-7.84855483e-01],
       [-4.76257253e-01],
       [ 5.33494305e-01],
       [-5.94250694e-01],
       [-6.35094577e-01],
       [-7.03167716e-01],
       [ 4.13231760e-01],
       [ 8.78398209e-01],
       [-9.21001760e-01],
       [ 5.49378038e-01],
       [-5.21639346e-01],
       [-3.53725604e-01],
       [ 2.95238320e-01],
       [-5.26177555e-01],
       [-1.34986253e+00],
       [-7.57626227e-01],
       [ 3.40620412e-01],
       [-2.90190674e-01],
       [-2.49346791e-01],
       [ 1.03042822e+00],
       [-5.21639346e-01],
       [-7.03167716e-01],
       [ 6.58295060e-01],
       [ 9.33113662e-03],
       [-3.40110976e-01],
       [-7.00875253e-02],
       [-6.75938461e-01],
       [ 2.32336403e+00],
       [ 6.58295060e-01],
       [-1.09027697e+00],
       [-4.49027998e-01],
       [ 1.69300677e+00],
       [ 7.74042754e-02],
       [ 6.58295060e-01],
       [-1.22276932e-01],
       [-1.04124095e-01],
       [ 6.03836549e-01],
       [-2.85652465e-01],
       [-1.01630415e+00],
       [ 1.69073766e+00],
       [-8.39313994e-01],
       [ 1.13709949e-01],
       [-9.01941281e-01],
       [-1.30448044e+00],
       [-4.96655837e-02],
       [-7.48549809e-01],
       [ 6.58295060e-01],
       [-9.59122718e-01],
       [-9.07387132e-01],
       [-6.78184207e-02],
       [ 4.94919527e-01],
       [ 3.86002505e-01],
       [ 1.59092042e-01],
       [-5.35253974e-01],
       [ 1.33902645e+00],
       [-4.76257253e-01],
       [-5.89712485e-01],
       [ 2.73452579e+00],
       [-4.85787493e-01],
       [ 1.20288017e+00],
       [ 7.94441337e-01],
       [ 6.35604013e-01],
       [-7.39473390e-01],
       [ 4.31384597e-01],
       [-9.75460271e-01],
       [ 4.04155342e-01],
       [-8.91503400e-01],
       [ 5.49378038e-01],
       [ 7.49059245e-01],
       [-3.62802022e-01],
       [-1.36347716e+00],
       [-1.03445699e+00],
       [-9.75460271e-01],
       [-7.84855483e-01],
       [-1.28178940e+00],
       [-3.40110976e-01],
       [-7.71240855e-01],
       [-7.84855483e-01],
       [ 1.56822937e-01],
       [-6.94091298e-01],
       [-2.94728883e-01],
       [-7.84855483e-01],
       [-5.67021438e-01],
       [-7.71240855e-01],
       [-4.78526358e-01],
       [ 4.31384597e-01],
       [ 3.86002505e-01],
       [ 7.77196142e-01],
       [ 1.97437574e+00],
       [ 1.11211599e+00],
       [-2.34824521e-01],
       [ 5.49378038e-01],
       [-2.94728883e-01],
       [ 2.54718117e-04],
       [-2.49346791e-01],
       [ 1.72931244e+00],
       [-1.23413820e+00],
       [-7.03167716e-01],
       [ 1.03950464e+00],
       [-8.59712577e-02],
       [ 3.86002505e-01],
       [ 5.22148782e-01],
       [ 7.67212082e-01],
       [-1.20237073e+00],
       [-5.36161616e-01],
       [-1.36347716e+00],
       [-2.94728883e-01],
       [-3.76416650e-01],
       [-6.89553088e-01],
       [ 7.26368199e-01],
       [-8.93772505e-01],
       [-6.85014879e-01],
       [ 3.86002505e-01],
       [-1.42247388e+00],
       [-1.13200513e-01],
       [-6.30556368e-01],
       [-7.48549809e-01],
       [ 2.04474134e-01],
       [ 1.02589001e+00],
       [-4.12722324e-01],
       [-7.48549809e-01],
       [ 1.20288017e+00],
       [-2.94728883e-01],
       [-9.79998480e-01],
       [ 8.39823430e-01],
       [-1.40429769e-01],
       [-9.57307434e-01],
       [-1.45197224e+00],
       [-8.91503400e-01],
       [-9.75460271e-01],
       [-1.17967969e+00],
       [-7.30396972e-01],
       [-9.75460271e-01],
       [-1.02991878e+00],
       [ 1.14842166e+00],
       [-3.61894380e-01],
       [ 2.13775128e+00],
       [ 9.10165673e-01],
       [-6.66862042e-01],
       [-7.48549809e-01],
       [ 4.81304899e-01],
       [-3.40110976e-01],
       [ 2.51896085e+00],
       [-6.85014879e-01],
       [-1.45197224e+00],
       [-1.13883580e+00],
       [-4.85333672e-01],
       [-5.00763583e-01],
       [-1.58582606e-01],
       [ 3.86002505e-01],
       [-8.93772505e-01],
       [-5.39792183e-01],
       [-5.89712485e-01],
       [-4.98948300e-01],
       [-3.62802022e-01],
       [-9.34616388e-01],
       [ 9.44656064e-01],
       [-3.76416650e-01],
       [ 3.86002505e-01],
       [ 1.36400996e-01],
       [-2.94728883e-01],
       [-5.03486509e-01],
       [ 1.59092042e-01]])